blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability Reporting
    url: https://github.com/Archetipo95/storybook-github-pages/security/policy
    about: Please report security vulnerabilities privately via our security policy.
